version: 2

jobs:
  build:
    working_directory: ~/test
    machine: true
    steps:
      - checkout
      - run:
          name: Docker info
          command: docker info
      - run:
          name: Build Docker image
          command: docker build -t nanshe/nanshe_notebook .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
